Source-Code-知宠网专业的网上宠物医院互动平台/Areas/User/Controllers/UserShopController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ZoomLa.AppCode.Filter;
using ZoomLa.BLL;
using ZoomLa.BLL.API;
using ZoomLa.BLL.Helper;
using ZoomLa.BLL.Shop;
using ZoomLa.Common;
using ZoomLa.Controls;
using ZoomLa.Model;
using ZoomLa.Model.Shop;
using ZoomLa.SQLDAL;
using ZoomLa.SQLDAL.SQL;
using ZoomLaCMS.Areas.User.Models;
using ZoomLaCMS.Models.Product;

namespace ZoomLaCMS.Areas.User.Controllers
{
    public class UserShopController : ZLCtrl
    {
        // GET: /User/UserShop/
        B_Store_Info storeBll = new B_Store_Info();
        OrderCommon orderCom = new OrderCommon();
        B_Content conBll = new B_Content();
        B_Model modBll = new B_Model();
        B_ModelField fieldBll = new B_ModelField();
        B_CartPro cartProBll = new B_CartPro();
        B_Product proBll = new B_Product();
        B_Node nodeBll = new B_Node();
        B_Stock stockBll = new B_Stock();
        B_OrderList orderBll = new B_OrderList();
        B_Shop_FareTlp fareBll = new B_Shop_FareTlp();
        B_Shop_RegionPrice regionBll = new B_Shop_RegionPrice();
        B_Payment payBll = new B_Payment();
        B_KeyWord keyBll = new B_KeyWord();
        B_Shop_DeliveryMan manBll = new B_Shop_DeliveryMan();
        B_Store_Style styleBll = new B_Store_Style();
        B_Order_Share shareBll = new B_Order_Share();
        B_Arrive avBll = new B_Arrive();
        B_Order_Exp expBll = new B_Order_Exp();
        public string Action { get { return DataConvert.CStr(Request.QueryString["Action"]).ToLower(); } }
        private int NodeID { get { return DataConverter.CLng(Request.QueryString["NodeID"]); } }
        private int ModelID { get { return DataConverter.CLng(Request.QueryString["ModelID"]); } }
        #region 店铺申请|信息修改
        public void Default() { Response.Redirect("Index"); return; }
        public ActionResult Index()
        {
            M_CommonData storeMod = conBll.SelMyStore(mu.UserName);
            if (storeMod == null)
            {
                return RedirectToAction("StoreApply");//申请店铺
            }
            else if (storeMod.Status != 99)//等待审核
            {
                return RedirectToAction("StoreEdit");
            }
            else
            {
                DataTable cmdinfo = conBll.GetContent(storeMod.GeneralID);
                if (cmdinfo.Rows.Count < 1) { function.WriteErrMsg("店铺信息不完整"); return Content(""); }
                DataRow dr = cmdinfo.Rows[0];
                //DataTable sstDT = sstbll.GetStyleByModel(Convert.ToInt32(dr["StoreModelID"]), 1);
                //M_StoreStyleTable sst = sstbll.GetStyleByID(Convert.ToInt32(dr["StoreStyleID"]));
                //ViewBag.sstdp = MVCHelper.ToSelectList(sstDT, "StyleName", "ID", dr["StoreStyleID"].ToString());
                ViewBag.dr = dr;
                //ViewBag.sstimg = sst == null ? "" : function.GetImgUrl(sst.StylePic);
                ViewBag.modelhtml = fieldBll.InputallHtml(DataConvert.CLng(dr["StoreModelID"]), 0, new ModelConfig()
                {
                    ValueDT = cmdinfo
                });
            }
            DataTable styleDt = styleBll.Sel();
            styleDt.Columns["ID"].ColumnName = "TemplateID";
            styleDt.Columns["Template_Index"].ColumnName = "TemplateUrl";
            styleDt.Columns["Thumbnail"].ColumnName = "TemplatePic";
            styleDt.Columns["StyleName"].ColumnName = "rname";
            ViewBag.styleDt = styleDt;
            return View(storeMod);
        }
        [ValidateInput(false)]
        //审核完成后,用户可自由修改店铺信息
        public void UserShop_Edit()
        {
            M_CommonData storeMod = conBll.SelMyStore(mu.UserName);
            DataTable cmdinfo = conBll.GetContent(storeMod.GeneralID);
            //----------
            DataTable dt = fieldBll.GetModelFieldList(Convert.ToInt32(cmdinfo.Rows[0]["StoreModelID"]));
            Call commonCall = new Call();
            DataTable table;
            try
            {
                table = commonCall.GetDTFromMVC(dt, Request);
            }
            catch (Exception e)
            {
                function.WriteErrMsg(e.Message); return;
            }
            storeMod.Title = Request.Form["StoreName_T"];
            storeMod.IP = IPScaner.GetUserIP();
            storeMod.DefaultSkins = DataConverter.CLng(Request.Form["TempleID_Hid"]);
            conBll.UpdateContent(table, storeMod);
            function.WriteSuccessMsg("提交成功", "Index"); 
        }
        public void StoreEdit() { Response.Redirect("StoreAuditing"); }
        public ActionResult StoreAuditing() { return View(); }
        [ValidateInput(false)]
        public ActionResult StoreApply()
        {
            DataTable moddt = modBll.GetListStore();
            M_CommonData storeMod = conBll.SelMyStore(mu.UserName);
            if (moddt.Rows.Count < 1) { function.WriteErrMsg("管理员未指定店铺申请模型"); return Content(""); }
            ViewBag.moddp = MVCHelper.ToSelectList(moddt, "ModelName", "ModelID");
            switch (Action)
            {
                case "edit":
                    {
                        if (storeMod == null) { function.WriteErrMsg("店铺申请不存在"); return null; }
                        //DataTable dtContent = conBll.GetContent(storeMod.GeneralID);
                        //ViewBag.modhtml = fieldBll.InputallHtml(storeMod.ModelID, 0, new ModelConfig()
                        //{
                        //    ValueDT = dtContent
                        //});
                    }
                    break;
                default:
                    {
                        //ViewBag.modhtml = fieldBll.InputallHtml(DataConvert.CLng(moddt.Rows[0]["ModelID"]), 0, new ModelConfig()
                        //{
                        //    Source = ModelConfig.SType.Admin
                        //});
                        //如果未开通则填写,已申请未审核则显示提示,已开通跳回index页
                        if (storeMod != null)
                        {
                            if (storeMod.Status != (int)ZLEnum.ConStatus.Audited) { return View("StoreAuditing"); }
                            else { RedirectToAction("Store_Edit"); }
                        }
                        else { storeMod = new M_CommonData() { ModelID = DataConvert.CLng(moddt.Rows[0]["ModelID"]) }; }
                    }
                    break;
            }
            DataTable styleDt = styleBll.Sel();
            styleDt.Columns["ID"].ColumnName = "TemplateID";
            styleDt.Columns["Template_Index"].ColumnName = "TemplateUrl";
            styleDt.Columns["Thumbnail"].ColumnName = "TemplatePic";
            styleDt.Columns["StyleName"].ColumnName = "rname";
            ViewBag.styleDt = styleDt;
            return View(storeMod);
        }
        [ValidateInput(false)]
        public ActionResult Apply_Add()
        {
            B_Store_Info stBll = new B_Store_Info();
            int modelid = DataConvert.CLng(Request.Form["model_dp"]);
            string store = Request.Form["store_t"];
            M_CommonData CData = conBll.SelMyStore(mu.UserName);
            if (CData == null) { CData = new M_CommonData(); }
            //----------------------------------------
            if (string.IsNullOrEmpty(store)) { function.WriteErrMsg("店铺名称不能为空"); return Content(""); }
            //M_StoreStyleTable sst = sstbll.GetNewStyle(modelid);
            //if (sst.ID == 0) { function.WriteErrMsg("后台没有为该模型绑定可用的模板!"); return Content(""); }
            CData.Title = HttpUtility.HtmlEncode(Request.Form["store_t"]);
            CData.DefaultSkins = DataConverter.CLng(Request.Form["TempleID_Hid"]);
            CData.ModelID = modelid;
            CData.TableName = modBll.SelReturnModel(CData.ModelID).TableName;
            CData.Inputer = mu.UserName;
            CData.SuccessfulUserID = mu.UserID;
            CData.Inputer = mu.UserName;
            CData.IP = IPScaner.GetUserIP();
            DataTable dt = fieldBll.GetModelFieldList(modelid);
            DataTable table = new Call().GetDTFromMVC(dt, Request);
            table = stBll.FillDT(CData, table);
            if (CData.GeneralID > 0) { conBll.UpdateContent(table, CData); }
            else { conBll.AddContent(table, CData); }
            return View("StoreAuditing");
        }
        [AF_StoreCheck]
        public void ViewMyStore()
        {
            M_Store_Info storeMod = storeBll.SelModelByUser(mu.UserID);
            Response.Redirect("/Store/StoreIndex?id=" + storeMod.ID); return;
        }
        #endregion
        #region 库存管理
        [AF_StoreCheck]
        public ActionResult StockList()
        {
            M_Store_Info storeMod = storeBll.SelModelByUser(mu.UserID);
            F_Stock filter = new F_Stock()
            {
                NodeID = DataConvert.CLng(Request["NodeID"]),
                ProID = DataConvert.CLng(Request["ProID"]),
                StockType = DataConvert.CLng(Request["StockType"]),
                StoreID = storeMod.ID,
                ProName = Request["ProName"],
                AddUser = Request["AddUser"],
                SDate = Request["SDate"],
                EDate = Request["EDate"]
            };
            PageSetting setting = stockBll.SelPage(CPage, PSize,filter);
            if (Request.IsAjaxRequest())
            {
                return PartialView("StockList_List", setting);
            }
            return View(setting);
        }
        [AF_StoreCheck]
        public ActionResult StockAdd()
        {
            int ProID = DataConvert.CLng(Request.QueryString["ProID"]);
            string action = DataConverter.CStr(Request.QueryString["action"]);
            M_Product proMod = Stock_GetProByID(mu, ProID);
            return View(proMod);
        }
        [AF_StoreCheck]
        public string Stock_Add()
        {
            M_Store_Info storeMod = storeBll.SelModelByUser(mu.UserID);

Source-Code-知宠网专业的网上宠物医院互动平台/Areas/User/Views/UserShop/AddDeliverMan.cshtml
@model ZoomLa.Model.Shop.M_Shop_DeliveryMan
@{
    
}
@section head{<title>添加送货人</title> }
@section content{
<div id="pageflag" data-nav="shop" data-ban="store"></div>
<nav aria-label="breadcrumb" role="navigation" class="container">
  <ol class="breadcrumb">
  	<li class="breadcrumb-item"><a title="会员中心" href="@Url.Action("Default","")">会员中心</a></li>
	<li class="breadcrumb-item"><a href="ProductList">我的店铺</a></li>
	<li class="breadcrumb-item"><a href="DeliveryMan">送货人管理</a></li>
	<li class="breadcrumb-item active" aria-current="page"><a href="ProductList">添加送货人</a></li>
  </ol>
</nav> 
<div class="container">
@Html.Partial("UserShopTop")
<form method="post" action="@MVCHelper.GetAction("DeliveryMan_Add",Request)">
	<table class="table table-bordered table-striped">
		<tr>
			<td class="text-right td_m">用户名/ID</td>
			<td>
				<input type="text" id="user" name="user" class="form-control text_300 required" value="@(Model.ID>0 ? Model.UserID.ToString() :"")" placeholder="请输入用户名或ID" />
			</td>
		</tr>
		<tr>
			<td class="text-right">权限</td>
			<td>
				<label>@Html.CheckBox("auth", Model.Auth.Contains("settle"), new { value = "settle" }) 结款</label>
			</td>
		</tr>
		<tr><td class="text-right">结算比率</td><td>
			@Html.TextBoxFor(p=>p.Bonus,new{Value=Model.Bonus.ToString("F2"),@class="form-control text_300"})
			</td></tr>
		<tr>
			<td class="text-right">备注</td>
			<td>
				@Html.TextAreaFor(p=>p.Remind,new { @class="form-control m715-50",@style="height:80px;"})
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<button type="submit" class="btn btn-info">保存信息</button>
			</td>
		</tr>
	</table>
</form>
</div>
<script>
//导航处理
	$("#usernav1 ul li").removeClass("active").siblings().eq(2).addClass("active");
</script>
}
@section script{
<link type="text/css" href="/dist/css/bootstrap-switch.min.css" rel="stylesheet" />
<script src="/dist/js/bootstrap-switch.js"></script>
}

Source-Code-知宠网专业的网上宠物医院互动平台/Areas/User/Views/UserShop/DeliveryMan.cshtml
@model ZoomLa.SQLDAL.SQL.PageSetting
@{
    
}
@section head{
    <title>送货员管理</title>
}
@section content{
<div id="pageflag" data-nav="shop" data-ban="store"></div>
<div class="container">
	<nav>
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a title="会员中心" href="/User/Default">会员中心</a></li>
        <li class="breadcrumb-item"><a href="ProductList">我的店铺</a></li>
        <li class="breadcrumb-item">配送员管理<a href="AddDeliverMan"> [添加配送员]</a></li>
    </ol>
	</nav>
    @Html.Partial("UserShopTop")
</div>
<div class="container">
    @Html.Partial("DeliveryMan_List", Model)
    <div>
        <button type="button" class="btn btn-outline-danger" onclick='mvcpage.bat({url: "DeliveryMan_Del", confirm: "确定要删除选中项吗？"});'>批量删除</button>
    </div>
</div>
<script>
//导航处理
	$("#usernav1 ul li").removeClass("active").siblings().eq(2).addClass("active");
</script>
}
@section script{

}

Source-Code-知宠网专业的网上宠物医院互动平台/Areas/User/Views/UserShop/DeliveryManOrder.cshtml
@model ZoomLa.SQLDAL.SQL.PageSetting
@{
    
}
@section head{
    <title>订单结算</title>
}
@section content{
<div id="pageflag" data-nav="shop" data-ban="store"></div>
<div class="container">
<nav aria-label="breadcrumb" role="navigation">
<ol class="breadcrumb">
	 <li class="breadcrumb-item"><a title="会员中心" href="/User/Default">会员中心</a></li>
	<li class="breadcrumb-item"><a href="ProductList">我的店铺</a></li>
	<li class="breadcrumb-item">订单结清</li>
</ol>
</nav>
</div>
<div class="container">
    @Html.Partial("DeliveryManOrder_List")
</div>
<script>
$(function(){
//导航处理
	$("#usernav1 ul li").removeClass("active").siblings().eq(2).addClass("active");
})
</script>
}
@section script{

}

Source-Code-知宠网专业的网上宠物医院互动平台/Areas/User/Views/UserShop/DeliveryManOrder_List.cshtml
@model ZoomLa.SQLDAL.SQL.PageSetting
@using System.Data
@using ZoomLa.BLL.Helper
@using ZoomLa.BLL.Shop
@using ZoomLa.Common
@{
    Model.cols = 8;
}
<table id="EGV" class="table table-bordered table-striped">
    <tr>
        <td class="td_s"></td>
        <td>ID</td>
        <td>店铺</td>
        <td>订单号</td>
        <td>客户名称</td>
        <td>已支付金额</td>
        <td>下单时间</td>
        <td>操作</td>
    </tr>
    @foreach (DataRow dr in Model.dt.Rows)
    {
        <tr>
            <td><input type="checkbox" name="idchk" value="@dr["ID"]" /></td>
            <td>@dr["ID"]</td>
            <td>@dr["StoreName"]</td>
            <td>@dr["OrderNo"]</td>
            <td>@dr["Rename"]</td>
            <td>@Convert.ToDouble(dr["Receivablesamount"]).ToString("F2")</td>
            <td>@DateHelper.ToDate(dr["AddTime"])</td>
            <td>
                <a href="/BU/Money/OrderSettle.aspx?ID=@dr["ID"]" class="btn btn-primary" >结算</a>
            </td>
        </tr>
    }
    @Html.Partial("_page", Model)
</table>

Source-Code-知宠网专业的网上宠物医院互动平台/Areas/User/Views/UserShop/DeliveryMan_List.cshtml
@using System.Data
@using ZoomLa.Common
@model ZoomLa.SQLDAL.SQL.PageSetting
@{
    Model.cols = 8;
}
@functions{
    public string GetAuth(string auth)
    {
        string result = "";
        if (auth.Contains("settle")) { result += "结款,"; }
        return result.Trim(',');
    }
}
<table id="EGV" class="table table-bordered table-striped">
    <tr>
        <td class="td_s"></td>
        <td>ID</td>
        <td>用户名</td>
        <td>姓名</td>
        <td>权限</td>
        <td>创建时间</td>
        <td>备注</td>
        <td>操作</td>
    </tr>
    @foreach (DataRow dr in Model.dt.Rows)
    {
        <tr>
            <td><input type="checkbox" name="idchk" value="@dr["ID"]" /></td>
            <td>@dr["ID"]</td>
            <td>@dr["UserName"]</td>
            <td>@dr["HoneyName"]</td>
            <td>@GetAuth(dr["Auth"].ToString())</td>
            <td>@DataConverter.CDate(dr["CDate"]).ToString("yyyy-MM-dd")</td>
            <td>@dr["Remind"]</td>
            <td>
                <a href="AddDeliverMan?id=@dr["ID"]"><i class="zi zi_pencilalt"></i>修改</a>
                <a href="javascript:;" onclick='mvcpage.del({ ids: @dr["id"], url: "DeliveryMan_Del",confirm:"确定要删除吗" });'><i class="zi zi_trashalt"></i>删除</a>
            </td>
        </tr>
    }
    @Html.Partial("_page", Model)
</table>

Source-Code-知宠网专业的网上宠物医院互动平台/Areas/User/Views/UserShop/ProductList.cshtml
@model ZoomLa.SQLDAL.SQL.PageSetting
@using ZoomLa.BLL
@using ZoomLa.Controls
@{
    B_Node nodeBll = new B_Node();
    C_TreeView treeMod = new C_TreeView()
    {
        NodeID = "NodeID",
        NodeName = "NodeName",
        NodePid = "ParentID",
        DataSource = nodeBll.GetAllUserShopNode(),
        liAllTlp = "<a href='ProductList'>全部商品</a>",
        LiContentTlp = "<a href='ProductList?NodeID=@NodeID'>@NodeName</a>",
        SelectedNode = Request["NodeID"]
    };
}
@section head{
<title>商品列表</title>
}
@section content{
<div id="pageflag" data-nav="shop" data-ban="store"></div> 
<div class="container">
<nav aria-label="breadcrumb" role="navigation">
  <ol class="breadcrumb">
  	<li class="breadcrumb-item"><a title="会员中心" href="@Url.Action("Default","")">会员中心</a></li>
	<li class="breadcrumb-item"><a href="ProductList">店铺商品管理</a></li>
  </ol>
</nav>
</div>
<main class="container">
    <div>@Html.Partial("UserShopTop")</div>
<div class="row">
    <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3 col-12" >
        @Html.Partial("_treeview",treeMod)
    </div>
    <div class="col-xl-9 col-lg-9 col-md-9 col-sm-9 col-12">
    <table class="table table-bordered" >
        <tbody>
            <tr>
                <td>
                    商品管理：
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                            商品管理 <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li class="dropdown-item"><a href="SelShopNode">添加商品</a></li>
                            <li class="dropdown-item"><a href="ProductList?type=0">商品管理</a></li>
                        </ul>
                    </div>
                    <input type="hidden" id="NodeID" value="@Request["NodeID"]" class="mvcparam"/>
                </td>
                <td width="66%" align="center">
                    <div class="input-group">
						<div class="input-group-prepend">
						<span class="input-group-text">高级查询</span>
					  </div>
                        <select ID="souchtable" class="form-control">
                            <option Value="1" selected="selected">商品名称</option>
                            <option Value="2">商品简介</option>
                            <option Value="3">商品介绍</option>
                            <option Value="4">厂商</option>
                            <option Value="5">品牌/商标</option>
                            <option Value="6">条形码</option>
                        </select>
                        <input type="text" ID="KeyWord" class="form-control mvcparam" placeholder="请输入关键词" />
                        <span class="input-group-append">
                            <input type="button" value="搜索" class="btn btn-outline-secondary" onclick="mvcpage.load();" />
                        </span>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
    <div class="commodity_listbox">
        @Html.Partial("ProductList_List",Model)
        <div class="shop_btnbox">
            <input type="button" value="保存排序" class="btn btn-outline-info" onclick="sort.save('product_op?a=order');"/>
            <input type="button" value="整理序列号" class="btn btn-outline-info" onclick="sort.reorder();" />
        </div>
        <div class="shop_btnbox">
            <input type="button" class="btn btn-info" value="开始销售" onclick="mvcpage.bat({ url: 'product_op?a=addsale', after: 'reload' });" />
            <input type="button" class="btn btn-info" value="设为热卖" onclick="mvcpage.bat({ url: 'product_op?a=addhot', after: 'reload' });" />
            <input type="button" class="btn btn-info" value="设为精品" onclick="mvcpage.bat({ url: 'product_op?a=addgood', after: 'reload' });" />
            <input type="button" class="btn btn-info" value="设为新品" onclick="mvcpage.bat({ url: 'product_op?a=addnew', after: 'reload' });" />
            <input type="button" class="btn btn-info" value="停止销售" onclick="mvcpage.bat({ url: 'product_sale?a=removesale', after: 'reload' });" />
            <input type="button" class="btn btn-info" value="取消热卖" onclick="mvcpage.bat({ url: 'product_sale?a=removehot', after: 'reload' });" />
            <input type="button" class="btn btn-info" value="取消精品" onclick="mvcpage.bat({ url: 'product_sale?a=removegood', after: 'reload' });" />
            <input type="button" class="btn btn-info" value="取消新品" onclick="mvcpage.bat({ url: 'product_sale?a=removenew', after: 'reload' });" />
            <input type="button" class="btn btn-outline-danger" value="批量删除" onclick="mvcpage.bat({ url: 'product_del',confirm:'确定要删除商品吗', after: 'reload' });" />
        </div>
    </div>
    </div>
</div>
</main>
}
@section script{
<script>
$(function () {
    if (getParam("quicksouch")) {
        $("li a[href='#Tabs" + getParam("quicksouch") + "']").parent().addClass("active").siblings("li").removeClass("active");
    }
})
var sort = {};
sort.up = function (id) {
    var $tr = $("#tr_" + id);
    var $pre = $tr.prev(".order_tr");
    if ($pre.length > 0) {
        //交换orderID和位置
        var temp = sort.getorder($tr);
        sort.setorder($tr, sort.getorder($pre));
        sort.setorder($pre, temp);
        $pre.before($tr);
    }
}
sort.down = function (id) {
    var $tr = $("#tr_" + id);
    var $next = $tr.next(".order_tr");
    if ($next.length > 0) {
        //交换orderID和位置
        var temp = sort.getorder($tr);
        sort.setorder($tr, sort.getorder($next));
        sort.setorder($next, temp);
        $next.after($tr);
    }
}
sort.reorder = function () {
    var $trs = $(".order_tr");
    for (var i = 0; i < $trs.length; i++) {
        $($trs[i]).find(".order_t").val((i + 1));
    }
}
sort.getorder = function ($tr) {
    return $tr.find(".order_t").val();
}
sort.setorder = function ($tr, order) {
    $tr.find(".order_t").val(order);
}
sort.save = function (url) {
    var list = [];
    $(".order_t").each(function () {
        var data = { "id": $(this).data("id"), "order": $(this).val() };
        if (parseInt(data.order) && parseInt(data.order) >= 0) {
            list.push(data);
        }
    });
    $.post(url, { "list": JSON.stringify(list),ids:"1,2,3" }, function (data) {
        location = location;
    })
}
//导航处理
	$("#usernav1 ul li").removeClass("active").siblings().eq(2).addClass("active");
</script>
}

Source-Code-知宠网专业的网上宠物医院互动平台/Areas/User/Views/UserShop/StoreApply.cshtml
@using ZoomLa.BLL
@using ZoomLaCMS.Models.Field
@using ZoomLa.AppCode.Controls
@using System.Data
@model ZoomLa.Model.M_CommonData
@{
    
    DataTable styleDt = ViewBag.styleDt;
}
@section head{
<title>我的店铺</title>
<script type="text/javascript" charset="utf-8" src="/Plugins/Ueditor/ueditor.config.js"></script>
<script type="text/javascript" charset="utf-8" src="/Plugins/Ueditor/ueditor.all.min.js"></script>
}
@section content{
<div id="pageflag" data-nav="shop" data-ban="store"></div>
<nav aria-label="breadcrumb" role="navigation" class="container">
  <ol class="breadcrumb">
	<li class="breadcrumb-item"><a title="会员中心" href="@Url.Action("Default","")">会员中心</a></li>
	<li class="breadcrumb-item active">店铺申请</li>
  </ol>
</nav>
<main class="container u_Sapply">
	@{Html.BeginForm("Apply_Add", "UserShop");}
	<ul class="fd_body">
		<li class="fd_item text-center">申请开通店铺</li>
		<li class="fd_item">
			<div class="fd_item_head"><div class="fd_alias">商铺名称</div><span class="fd_item_req">*</span></div>
			<div class="fd_item_field">
				<input type="text" name="store_t" class="form-control m715-50 required" value="@Model.Title" />
			</div>
		</li>
		<li class="fd_item">
			<div class="fd_item_head"><div class="fd_alias">商铺类型</div><span class="fd_item_req">*</span></div>
			<div class="fd_item_field">
				@Html.DropDownList("model_dp", ViewBag.moddp as SelectList, new { @class = "form-control text_md" })
			</div>
		</li>
		<li class="fd_item">
			<div class="fd_item_head"><div class="fd_alias">商铺样式</div><span class="fd_item_req">*</span></div>
			<div class="fd_item_field">
				@Html.Partial("C_TemplateView", new C_TemplateView(styleDt))
				<div class="clearfix"></div>
			</div>
		</li>
		@Html.Partial("Fields/Index_User_AddContent", new VM_FieldModel(Model.ModelID, Model.NodeID, new ModelConfig() { Source = ModelConfig.SType.Admin }, Model.GeneralID))
	</ul>
	<div class="text-center">
		<input type="submit" class="btn btn-info" value="信息提交" />
		<a href="@Url.Action("","Info")" class="btn btn-outline-info">返回</a>
	</div>
	@{Html.EndForm();}
</main>
}
@section script{
<script src="/js/Common.js"></script>
<script src="/JS/DatePicker/WdatePicker.js"></script>
<script src="/JS/Controls/ZL_Dialog.js"></script>
<script src="/js/ZL_Content.js"></script>
<script>
	$(function () {
		$("form").validate();
		//导航处理
		$("#usernav1 ul li").removeClass("active").siblings().eq(2).addClass("active");
	})
</script>
}